### notes
GET http://localhost:3000/notes
###
POST http://localhost:3000/notes
Content-Type: application/json

{
  "name": "Note"
}
###
PATCH http://localhost:3000/notes/1
Content-Type: application/json

{
  "name": "Note"
}
###
DELETE http://localhost:3000/notes/1


### fields
GET http://localhost:3000/fields
###
GET http://localhost:3000/fields/1
###
POST http://localhost:3000/fields
Content-Type: application/json

{
  "name": "Field",
  "content": "Content",
  "attachment": "Attachment",
  "note_id": 1
}
###
PATCH http://localhost:3000/fields/16
Content-Type: application/json

{
  "name": "Field",
  "content": "Content",
  "attachment": "Attachment"
}
###
DELETE http://localhost:3000/fields/1